// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwrsRXQGJ6JhLFCfEx6oe2PUPFEk0J0Aw',
    appId: '1:252527930256:web:603526ec43050209aba115',
    messagingSenderId: '252527930256',
    projectId: 'authapp-20107',
    authDomain: 'authapp-20107.firebaseapp.com',
    storageBucket: 'authapp-20107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMX9k9BBzm0mROhByHR94JiqOW4osC3Qw',
    appId: '1:252527930256:android:5a12d760def5ebbaaba115',
    messagingSenderId: '252527930256',
    projectId: 'authapp-20107',
    storageBucket: 'authapp-20107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRu60c5Mpy-eR9x_icLEFGd5YODnSbcTQ',
    appId: '1:252527930256:ios:1c02d16efde6c82aaba115',
    messagingSenderId: '252527930256',
    projectId: 'authapp-20107',
    storageBucket: 'authapp-20107.appspot.com',
    androidClientId: '252527930256-0dl6fpn0gctfgve7mcgjoobssgmk33tg.apps.googleusercontent.com',
    iosClientId: '252527930256-833v1ui7gaqatm5q7m0ae7vsbhqtiasn.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
